### ISSUE TITLE
Lifecycles methods (@PostConstruct, @PreDestroy) only work with bind()

### ISSUE THREAD

**Issue by MrBuddyCasino** [embulk/guice-bootstrap#16]
Instances contributed via a provider do not have their lifecycle methods invoked.

This works:
```
  @Override
  protected void configure() {
    // Guice lifecycle support apparently only works via bind(), not providers!
    bind(KafkaContainer.class).toInstance(new KafkaContainer());
  }
```

This doesn't:
```
  @Provides
  @Singleton
  public KafkaContainer kafkaContainer() {
    return new KafkaContainer();
  }
```

Tested with v0.3.2.

**Comment by masoudamri** [comment]
I've run into the same issue.

Is anyone planning on fixing this?

**Comment by MrBuddyCasino** [comment]
I don't think this will happen without someone creating a PR, given the age of the issue.

**Comment by joschi** [comment]
This seems to be a (breaking) change introduced in Guice 4.1: https://github.com/google/guice/wiki/Guice41#guice-core

> TypeListeners no longer get invoked for `Provider` instances that Guice generates for `@Provides` methods.

**Comment by dmikurube** [comment]
This `guice-bootstrap` is no longer maintained. If you still need the improvement, consider forking it and maintain the fork by yourself.
